### ISSUE TITLE
spkg-duo: Failed to compile setuptools-69.2.0

### ISSUE THREAD

**Issue by dslm4515** [dslm4515/MLFS-pkgtool#11]
Under choot & building the rest of the toolchain, setuptools python module fails to compile:

```
Processing /sources/setuptools-69.2.0
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [82 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-svcxq0ao/setuptools.egg-info
      writing /tmp/pip-modern-metadata-svcxq0ao/setuptools.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-svcxq0ao/setuptools.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-modern-metadata-svcxq0ao/setuptools.egg-info/entry_points.txt
      writing requirements to /tmp/pip-modern-metadata-svcxq0ao/setuptools.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-svcxq0ao/setuptools.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-svcxq0ao/setuptools.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-svcxq0ao/setuptools.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.py' under directory 'tests'
      warning: no files found matching '*.txt' under directory 'docs'
      warning: no files found matching '*.conf' under directory 'docs'
      warning: no files found matching '*.css' under directory 'docs'
      warning: no files found matching '*.css_t' under directory 'docs'
      warning: no files found matching 'Makefile' under directory 'docs'
      warning: no files found matching 'indexsidebar.html' under directory 'docs'
      warning: no files found matching 'msvc-build-launcher.cmd'
      warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
      warning: no previously-included files matching '__pycache__' found anywhere in distribution
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-modern-metadata-svcxq0ao/setuptools.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-svcxq0ao/setuptools-69.2.0.dist-info'
      Traceback (most recent call last):
        File "/llvmtools/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/llvmtools/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/llvmtools/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/sources/setuptools-69.2.0/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/sources/setuptools-69.2.0/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 93, in <module>
        File "/sources/setuptools-69.2.0/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/sources/setuptools-69.2.0/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/sources/setuptools-69.2.0/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/sources/setuptools-69.2.0/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/sources/setuptools-69.2.0/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/sources/setuptools-69.2.0/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/sources/setuptools-69.2.0/setuptools/command/dist_info.py", line 97, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/sources/setuptools-69.2.0/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/sources/setuptools-69.2.0/setuptools/_distutils/dist.py", line 860, in get_command_obj
          klass = self.get_command_class(command)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/sources/setuptools-69.2.0/setuptools/dist.py", line 714, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
                                              ^^^^^^^^^
        File "/llvmtools/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
          module = import_module(match.group('module'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/llvmtools/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/llvmtools/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 27, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/llvmtools/lib/python3.12/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/llvmtools/lib/python3.12/ctypes/__init__.py", line 8, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

Even after building the Wheel module prior.

**Comment by dslm4515** [comment]
Build libffi first? No change

**Comment by dslm4515** [comment]
Rebuild python with libffi installed?

python configure warns: `WARNING: pkg-config is missing. Some dependencies may not be detected correctly.`

Build pkgconf before python? No need: No build errors for python.

After rebuilding python with libffi installed, now setuptools builds fine.

May need to build libffi before python [for the toolschain /tools or /llvmtools]

**Comment by dslm4515** [comment]
Looks no need to build libffi before python3.
setuptools-82.0.1 compiled fine for the tool chain of a Forked-LFS build.
Haven't confirmed if this is true for llvmtools of a CMLFS build.
