### ISSUE TITLE
Meson will not configure

### ISSUE THREAD

**Issue by dslm4515** [dslm4515/MLFS-pkgtool#4]
With Python 3.8.0, meson errors out:
```
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    from setuptools import setup
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
    from setuptools import windows_support
  File "/usr/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```
command that was run:
`python3 setup.py build`

**Comment by dslm4515** [comment]
Looks like libffi was not built, packaged and installed on system

edit: typo

**Comment by dslm4515** [comment]
Confirmed: meson needs libffi installed
